```yaml
name: CI-CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  # ==========================================
  # CI - BUILD AND PUSH DOCKER IMAGE TO ECR
  # ==========================================

  build-and-push:
    name: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t argo:latest .

      - name: Tag Docker Image
        run: |
          docker tag argo:latest \
            455880746048.dkr.ecr.ap-south-1.amazonaws.com/argo:latest

      - name: Push Image to ECR
        run: |
          docker push \
            455880746048.dkr.ecr.ap-south-1.amazonaws.com/argo:latest


  # ==========================================
  # CD - DEPLOY DOCKER IMAGE TO EC2
  # ==========================================
